apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: clavance/udagram-api-feed
        ports:
        - containerPort: 8080
        env:
        - name: AWS_PGUSERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_PGUSERNAME
        - name: AWS_PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_PGPASSWORD
        - name: AWS_PGDATABASE
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_PGDATABASE
        - name: AWS_PGHOST
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_PGHOST
        - name: URL
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: URL
