version: '3'
services:
  udagram-api-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: clavance/udagram-api-user
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: clavance/udagram-api-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: clavance/udagram-frontend
